[features]
seeds = false
[programs.localnet]
transfer = "H7osZtwGvXjiW1JMeGNbVY8SmoxuADP1vQg3PmG2u2gp"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./test-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
